---
title: "MS Incidence Rate Over Time By Sex"
execute: 
  echo: false
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(plotly)
library(wesanderson)
```

```{r}
#| label: import_data

# Brought downloaded CSV file with data into project through terminal. Turned
# CSV file into data frame. Kept only the data that combined all age groups
# together to see the general trend in incidence rates over time.

ms_data <- read_csv("DataFilterExport.csv", show_col_types = FALSE)
ms_data_clean_time <- ms_data |>
  filter(Age == "ALL")
```

```{r}
#| label: create_line_graph

# Created line graph to show trend of MS Incidence Rates in Alberta over time.
# Tried bar graph but decided on line graph so trend was more apparent. Created
# lines for each of the Sex categories to see the effect of Sex on incidence
# rate change over time. Used Wes Anderson Palettes R package for colors in line
# graph. Opted not to add title since it was the same as the page and subtitle
# since key takeaways were listed in paragraph below. Used minimal theme for
# clean look.

ms_line <-
  ms_data_clean_time |>
  ggplot(aes(x = Year, y = `Incidence Rate`, color = Sex)) +
  geom_line(linewidth = 0.75) +
  scale_color_manual(values = wes_palette("Cavalcanti1")[c(4, 1, 5)]) +
  labs(x = "Year", 
       y = "Incidence Rate (per 100 000)", 
       color = "Sex") +
  theme_minimal()

# Used plotly package to make graph interactive. Added caption to provide source
# of data, and adjusted sizing and placement of caption. Displayed line graph.

interactive_line <- 
  ggplotly(ms_line, tooltip = c("Year", "Incidence Rate")) |>
    layout( annotations = list(
      text = "Data from Alberta IHDA",
      x = 1, y = -0.25,
      xref = "paper", yref = "paper",
      showarrow = FALSE,
      font = list(size = 12)), 
      margin = list(b = 100))

interactive_line
```

In general, the incidence rate of MS in Alberta has decreased in the past 18 years, but while the incidence rate for women has had a relatively significant decrease, the incidence rate for men has increased in previous years to the point where there is not a significant difference in the rate from 2004 to 2022. Women continue to be more affected by MS than men. 
